"""MCP tools for querying the ML strategy analytics database."""

import json

from mcp.server.fastmcp import Context

from ib_mcp.analytics_db import (
    get_cross_strategy_view,
    get_execution_quality_report,
    get_latest_dashboard,
    get_model_metrics_history,
    get_pnl_curve,
    get_recent_signals,
    get_regime_history,
    get_signal_quality_summary,
)
from ib_mcp.server import mcp


@mcp.tool()
async def get_strategy_signals(
    strategy_id: str = "", symbol: str = "", limit: int = 50, ctx: Context = None,
) -> str:
    """Get recent ML signals generated by strategies with model metadata.

    Shows probability, features, scanner rank, confidence tier, and whether
    the signal was acted on. Filter by strategy_id or symbol.
    """
    signals = get_recent_signals(strategy_id, symbol, limit)
    return json.dumps(signals, indent=2) if signals else "No signals logged yet."


@mcp.tool()
async def get_execution_quality(
    strategy_id: str = "", limit: int = 50, ctx: Context = None,
) -> str:
    """Get execution quality metrics: slippage, fill time, spread analysis.

    Shows per-trade execution details including intended vs fill price,
    slippage percentage, and market impact.
    """
    report = get_execution_quality_report(strategy_id, limit)
    return json.dumps(report, indent=2) if report else "No execution data logged yet."


@mcp.tool()
async def get_model_performance(
    strategy_id: str = "", model_name: str = "", limit: int = 20, ctx: Context = None,
) -> str:
    """Get model accuracy, calibration, and feature importance over time.

    Shows how ML model metrics are trending — accuracy, precision, recall,
    AUC-ROC, and signal hit rate per strategy.
    """
    metrics = get_model_metrics_history(strategy_id, model_name, limit)
    return json.dumps(metrics, indent=2) if metrics else "No model metrics logged yet."


@mcp.tool()
async def get_cross_strategy_signals(
    symbol: str = "", limit: int = 50, ctx: Context = None,
) -> str:
    """See which strategies agree or disagree on the same symbols.

    Shows agreement score (0-1), bullish/bearish counts, and actual outcomes
    when multiple strategies signal on the same ticker.
    """
    view = get_cross_strategy_view(symbol, limit)
    return json.dumps(view, indent=2) if view else "No cross-strategy data logged yet."


@mcp.tool()
async def get_market_regime(limit: int = 20, ctx: Context = None) -> str:
    """Get market regime history: VIX, SPY, breadth, scanner state.

    Shows how the regime classification evolved — rally, chop, selloff, etc.
    Includes advance/decline ratio, scanner churn, and sector leadership.
    """
    regimes = get_regime_history(limit)
    return json.dumps(regimes, indent=2) if regimes else "No regime data logged yet."


@mcp.tool()
async def get_live_dashboard(ctx: Context = None) -> str:
    """Get the real-time portfolio and strategy dashboard.

    Pre-computed summary: open positions, P&L, regime, signal count, job health.
    Shows best/worst positions and per-strategy breakdown.
    """
    dash = get_latest_dashboard()
    return json.dumps(dash, indent=2) if dash else "No dashboard data yet. Run update_analytics_dashboard first."


@mcp.tool()
async def get_strategy_equity_curve(
    strategy_id: str = "", days: int = 30, ctx: Context = None,
) -> str:
    """Get the equity curve for a strategy over N days.

    Shows daily P&L, cumulative P&L, high water mark, drawdown,
    and rolling Sharpe ratio.

    Args:
        strategy_id: Strategy to query (e.g. "ml_rank_velocity"). Required.
        days: Number of days of history (default 30).
    """
    if not strategy_id:
        return "Please provide a strategy_id."
    curve = get_pnl_curve(strategy_id, days)
    return json.dumps(curve, indent=2) if curve else f"No P&L curve data for {strategy_id}."


@mcp.tool()
async def get_signal_quality(strategy_id: str = "", ctx: Context = None) -> str:
    """Get signal quality breakdown per strategy.

    Shows how often each strategy's signals lead to profitable trades:
    total signals, acted on, profitable, hit rate, average P&L.
    """
    summary = get_signal_quality_summary(strategy_id)
    return json.dumps(summary, indent=2) if summary else "No signal quality data yet."
