"""Backtesting engine for scanner-driven trading strategies.

Replays historical scanner data day-by-day, generates signals per strategy,
evaluates forward returns using minute bar data, and computes P&L.
"""

import csv
import json
import logging
import sqlite3
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from typing import Callable

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

SCANNER_BASE = Path("//Station001/DATA/hvlf/rotating")
BAR_DATA_BASE = Path("D:/Data/Strategies/HVLF/MinuteBars_SB")
DB_PATH = Path("D:/src/ai/mcp/ib/backtest/backtest_results.db")

SCANNER_TYPES = [
    "GainSinceOpen", "HighOpenGap", "HotByPrice", "HotByPriceRange",
    "HotByVolume", "LossSinceOpen", "LowOpenGap", "MostActive",
    "TopGainers", "TopLosers", "TopVolumeRate",
]
CAP_TIERS = ["LargeCap", "MidCap", "SmallCap"]

GAINER_SCANNERS = {"GainSinceOpen", "TopGainers", "HighOpenGap"}
LOSER_SCANNERS = {"LossSinceOpen", "TopLosers", "LowOpenGap"}
VOLUME_SCANNERS = {"HotByVolume", "MostActive", "TopVolumeRate"}


@dataclass
class ScannerSnapshot:
    """A single scanner snapshot at a point in time."""
    timestamp: datetime
    scanner_name: str  # e.g. "LargeCap-GainSinceOpen"
    cap_tier: str
    scanner_type: str
    symbols: list[dict]  # [{"rank": 0, "symbol": "NVDA"}, ...]


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    timestamp: datetime
    symbol: str
    strategy_id: str
    direction: str  # "LONG" or "SHORT"
    confidence: float  # 0-1
    scanners_present: list[str]
    metadata: dict = field(default_factory=dict)


@dataclass
class Trade:
    """A simulated trade from a backtest."""
    signal: Signal
    entry_time: datetime
    entry_price: float
    exit_time: datetime | None = None
    exit_price: float | None = None
    exit_reason: str = ""
    pnl: float = 0.0
    pnl_pct: float = 0.0
    max_favorable: float = 0.0
    max_adverse: float = 0.0
    hold_minutes: float = 0.0
    # Forward return tracking
    return_15m: float | None = None
    return_30m: float | None = None
    return_60m: float | None = None
    return_eod: float | None = None


@dataclass
class StrategyResult:
    """Aggregated results for a strategy backtest."""
    strategy_id: str
    strategy_name: str
    total_signals: int = 0
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    win_rate: float = 0.0
    total_pnl: float = 0.0
    avg_pnl_pct: float = 0.0
    avg_win_pct: float = 0.0
    avg_loss_pct: float = 0.0
    profit_factor: float = 0.0
    max_drawdown_pct: float = 0.0
    sharpe_ratio: float = 0.0
    avg_hold_minutes: float = 0.0
    expectancy: float = 0.0
    trades: list[Trade] = field(default_factory=list)
    daily_pnl: dict = field(default_factory=dict)


class PriceCache:
    """Cache for minute bar data. Loads from CSV files first, falls back to IB MCP."""

    def __init__(self, ib_client=None, disable_ib: bool = False):
        self._cache: dict[str, pd.DataFrame] = {}
        self._ib = ib_client  # Optional ib_insync.IB instance
        self._disable_ib = disable_ib  # If True, never attempt IB fetch
        self._fetch_failures: set[str] = set()  # Track symbols that failed IB fetch
        self._ib_connect_failed = False  # True after first IB connection failure

    def set_ib_client(self, ib):
        """Set IB client for fallback data fetching."""
        self._ib = ib

    def _load_from_csv(self, symbol: str, min_date: str = "20260101") -> pd.DataFrame | None:
        """Try loading minute bars from local CSV file.

        Only loads rows from min_date onwards to avoid OOM on large files.
        """
        path = BAR_DATA_BASE / f"{symbol}_STK_M.csv"
        if not path.exists():
            return None
        try:
            # Read in chunks to filter by date early and avoid OOM
            chunks = []
            for chunk in pd.read_csv(
                path, dtype={"Date": str, "Time": str},
                chunksize=100_000, on_bad_lines="skip",
            ):
                chunk.columns = [c.strip('"').lower() for c in chunk.columns]
                # Only keep recent data (scanner period starts 20260128)
                filtered = chunk[chunk["date"] >= min_date]
                if not filtered.empty:
                    chunks.append(filtered)

            if not chunks:
                return None

            df = pd.concat(chunks, ignore_index=True)
            df["datetime"] = pd.to_datetime(
                df["date"] + " " + df["time"], format="%Y%m%d %H:%M"
            )
            df = df.set_index("datetime").sort_index()
            return df
        except Exception as e:
            logger.warning(f"Failed to load CSV bars for {symbol}: {e}")
            return None

    def _fetch_from_ib(self, symbol: str, date: str = "") -> pd.DataFrame | None:
        """Fetch minute bars from IB via ib_insync. Blocking call."""
        if self._ib is None or self._disable_ib:
            return None
        if symbol in self._fetch_failures:
            return None

        try:
            import asyncio
            from ib_insync import Stock

            contract = Stock(symbol, "SMART", "USD")
            self._ib.qualifyContracts(contract)

            # Determine duration based on whether we need a specific date
            if date:
                end_dt = datetime.strptime(date, "%Y%m%d").replace(hour=20, minute=0)
                end_str = end_dt.strftime("%Y%m%d %H:%M:%S")
                duration = "1 D"
            else:
                end_str = ""
                duration = "5 D"

            bars = self._ib.reqHistoricalData(
                contract, endDateTime=end_str, durationStr=duration,
                barSizeSetting="1 min", whatToShow="TRADES", useRTH=False,
            )

            if not bars:
                self._fetch_failures.add(symbol)
                return None

            rows = []
            for b in bars:
                dt = b.date if isinstance(b.date, datetime) else datetime.fromisoformat(str(b.date))
                rows.append({
                    "date": dt.strftime("%Y%m%d"),
                    "time": dt.strftime("%H:%M"),
                    "open": b.open,
                    "high": b.high,
                    "low": b.low,
                    "close": b.close,
                    "volume": b.volume,
                    "datetime": dt,
                })

            df = pd.DataFrame(rows).set_index("datetime").sort_index()
            logger.info(f"Fetched {len(df)} bars from IB for {symbol}")
            return df

        except Exception as e:
            logger.warning(f"IB fetch failed for {symbol}: {e}")
            self._fetch_failures.add(symbol)
            return None

    def _fetch_from_ib_mcp(self, symbol: str, date: str = "") -> pd.DataFrame | None:
        """Fetch minute bars by auto-connecting to IB if not already connected."""
        if self._disable_ib or self._ib_connect_failed:
            return None

        if self._ib is not None:
            return self._fetch_from_ib(symbol, date)

        # Try auto-connecting to IB
        try:
            from ib_insync import IB
            ib = IB()
            try:
                ib.connect("127.0.0.1", 7497, clientId=99, timeout=4)
                self._ib = ib
                logger.info("Auto-connected to IB TWS (port 7497)")
            except Exception:
                try:
                    ib.connect("127.0.0.1", 4002, clientId=99, timeout=4)
                    self._ib = ib
                    logger.info("Auto-connected to IB Gateway (port 4002)")
                except Exception:
                    self._ib_connect_failed = True
                    logger.info("IB not available — using local CSV bars only")
                    return None

            return self._fetch_from_ib(symbol, date)

        except ImportError:
            self._disable_ib = True
            return None
        except Exception:
            self._ib_connect_failed = True
            return None

    def get_bars(self, symbol: str, date: str = "") -> pd.DataFrame | None:
        """Get minute bars for a symbol.

        Loads from local CSV first. If not found, fetches from IB MCP.
        Results are cached for subsequent lookups.

        Args:
            symbol: Ticker symbol
            date: Optional YYYYMMDD filter

        Returns:
            DataFrame with columns: date, time, open, high, low, close, volume
            Index is a datetime combining date+time
        """
        cache_key = symbol if not date else f"{symbol}_{date}"

        if cache_key not in self._cache:
            # Try 1: Local CSV file
            df = self._load_from_csv(symbol)

            if df is not None:
                self._cache[symbol] = df
            else:
                # Try 2: Fetch from IB (direct or via MCP)
                if not self._disable_ib and not self._ib_connect_failed:
                    logger.info(f"No local bars for {symbol}, fetching from IB...")
                df = self._fetch_from_ib(symbol, date)
                if df is None:
                    df = self._fetch_from_ib_mcp(symbol, date)
                if df is not None:
                    # Merge with existing cache if present
                    if symbol in self._cache:
                        self._cache[symbol] = pd.concat(
                            [self._cache[symbol], df]
                        ).drop_duplicates().sort_index()
                    else:
                        self._cache[symbol] = df
                else:
                    return None

        df = self._cache.get(symbol)
        if df is None or df.empty:
            return None
        if date:
            mask = df["date"] == date
            if mask.any():
                return df[mask]
            # Date not in cache — try fetching just this date from IB
            if symbol not in self._fetch_failures:
                df_date = self._fetch_from_ib(symbol, date)
                if df_date is not None and not df_date.empty:
                    self._cache[symbol] = pd.concat(
                        [self._cache[symbol], df_date]
                    ).drop_duplicates().sort_index()
                    return df_date
            return None
        return df

    def get_price_at(self, symbol: str, dt: datetime) -> float | None:
        """Get the closest price at or after a given datetime."""
        df = self.get_bars(symbol)
        if df is None or df.empty:
            return None
        mask = df.index >= dt
        if mask.any():
            return float(df.loc[mask].iloc[0]["close"])
        return None

    def get_forward_returns(
        self, symbol: str, entry_time: datetime, entry_price: float,
        horizons_minutes: list[int] = [15, 30, 60],
    ) -> dict[int, float | None]:
        """Compute forward returns at various time horizons."""
        df = self.get_bars(symbol)
        if df is None or df.empty:
            return {h: None for h in horizons_minutes}

        results = {}
        for h in horizons_minutes:
            target_time = entry_time + timedelta(minutes=h)
            mask = df.index >= target_time
            if mask.any():
                future_price = float(df.loc[mask].iloc[0]["close"])
                results[h] = (future_price - entry_price) / entry_price
            else:
                results[h] = None
        return results

    def get_eod_price(self, symbol: str, date: str) -> float | None:
        """Get end-of-day closing price."""
        df = self.get_bars(symbol, date)
        if df is None or df.empty:
            return None
        return float(df.iloc[-1]["close"])

    def get_mfe_mae(
        self, symbol: str, entry_time: datetime, entry_price: float,
        hold_minutes: int = 60, direction: str = "LONG",
    ) -> tuple[float, float]:
        """Compute max favorable and adverse excursion during hold period."""
        df = self.get_bars(symbol)
        if df is None or df.empty:
            return 0.0, 0.0

        end_time = entry_time + timedelta(minutes=hold_minutes)
        mask = (df.index >= entry_time) & (df.index <= end_time)
        period = df.loc[mask]

        if period.empty:
            return 0.0, 0.0

        if direction == "LONG":
            mfe = (period["high"].max() - entry_price) / entry_price
            mae = (entry_price - period["low"].min()) / entry_price
        else:
            mfe = (entry_price - period["low"].min()) / entry_price
            mae = (period["high"].max() - entry_price) / entry_price

        return float(mfe), float(mae)


def parse_scanner_line(line: str) -> dict:
    """Parse a scanner CSV line into timestamp + ranked symbols."""
    parts = line.strip().split(",")
    if not parts:
        return {}
    timestamp_str = parts[0].strip()
    symbols = []
    for entry in parts[1:]:
        pieces = entry.split(":")
        if len(pieces) == 2:
            try:
                rank = int(pieces[0])
            except ValueError:
                continue
            sym = pieces[1].replace("_STK", "").strip()
            if sym and " " not in sym:
                symbols.append({"rank": rank, "symbol": sym})
    return {"timestamp": timestamp_str, "symbols": symbols}


def load_day_scanner_data(date: str) -> list[ScannerSnapshot]:
    """Load all scanner snapshots for a given date."""
    date_dir = SCANNER_BASE / date
    if not date_dir.exists():
        return []

    snapshots = []
    for cap_tier in CAP_TIERS:
        for scanner_type in SCANNER_TYPES:
            filepath = date_dir / f"{cap_tier}-{scanner_type}_Scanner.csv"
            if not filepath.exists():
                continue
            with open(filepath, "r") as f:
                for line in f:
                    if not line.strip():
                        continue
                    parsed = parse_scanner_line(line)
                    if not parsed:
                        continue
                    try:
                        ts = datetime.strptime(
                            parsed["timestamp"].strip(),
                            "%Y%m%d %H:%M:%S.%f"
                        )
                    except ValueError:
                        continue

                    snapshots.append(ScannerSnapshot(
                        timestamp=ts,
                        scanner_name=f"{cap_tier}-{scanner_type}",
                        cap_tier=cap_tier,
                        scanner_type=scanner_type,
                        symbols=parsed["symbols"],
                    ))

    snapshots.sort(key=lambda s: s.timestamp)
    return snapshots


def build_symbol_state(
    snapshots: list[ScannerSnapshot],
    window_end: datetime,
    window_minutes: int = 10,
) -> dict[str, dict]:
    """Build current state for each symbol based on recent snapshots.

    Returns a dict mapping symbol -> state dict with:
    - scanners_present: set of scanner names the symbol is on
    - scanner_types: set of scanner types
    - ranks: dict of scanner_name -> rank
    - gainer_count, loser_count, volume_count
    - first_seen: earliest timestamp in window
    - rank_history: dict of scanner_name -> list of recent ranks
    """
    window_start = window_end - timedelta(minutes=window_minutes)
    recent = [s for s in snapshots if window_start <= s.timestamp <= window_end]

    states: dict[str, dict] = {}
    for snap in recent:
        for sym_entry in snap.symbols:
            sym = sym_entry["symbol"]
            if sym not in states:
                states[sym] = {
                    "scanners_present": set(),
                    "scanner_types": set(),
                    "ranks": {},
                    "rank_history": {},
                    "first_seen": snap.timestamp,
                    "last_seen": snap.timestamp,
                    "gainer_count": 0,
                    "loser_count": 0,
                    "volume_count": 0,
                    "cap_tiers": set(),
                }
            s = states[sym]
            s["scanners_present"].add(snap.scanner_name)
            s["scanner_types"].add(snap.scanner_type)
            s["cap_tiers"].add(snap.cap_tier)
            s["ranks"][snap.scanner_name] = sym_entry["rank"]
            s["last_seen"] = max(s["last_seen"], snap.timestamp)

            if snap.scanner_name not in s["rank_history"]:
                s["rank_history"][snap.scanner_name] = []
            s["rank_history"][snap.scanner_name].append(sym_entry["rank"])

    # Compute category counts
    for sym, s in states.items():
        s["gainer_count"] = len(s["scanner_types"] & GAINER_SCANNERS)
        s["loser_count"] = len(s["scanner_types"] & LOSER_SCANNERS)
        s["volume_count"] = len(s["scanner_types"] & VOLUME_SCANNERS)
        s["total_scanners"] = len(s["scanners_present"])

    return states


def compute_scanner_population_metrics(
    snapshots: list[ScannerSnapshot],
    timestamp: datetime,
    window_minutes: int = 5,
) -> dict:
    """Compute scanner population metrics for anomaly detection (Strategy 20).

    Returns per-scanner-type metrics: population count, newcomer ratio,
    dropout ratio, rank entropy.
    """
    window_start = timestamp - timedelta(minutes=window_minutes)
    prior_start = window_start - timedelta(minutes=window_minutes)

    current_window = [s for s in snapshots if window_start <= s.timestamp <= timestamp]
    prior_window = [s for s in snapshots if prior_start <= s.timestamp <= window_start]

    metrics = {}
    for scanner_type in SCANNER_TYPES:
        current_syms = set()
        prior_syms = set()
        current_ranks = []

        for snap in current_window:
            if snap.scanner_type == scanner_type:
                for sym in snap.symbols:
                    current_syms.add(sym["symbol"])
                    current_ranks.append(sym["rank"])

        for snap in prior_window:
            if snap.scanner_type == scanner_type:
                for sym in snap.symbols:
                    prior_syms.add(sym["symbol"])

        population = len(current_syms)
        newcomers = len(current_syms - prior_syms) if prior_syms else 0
        dropouts = len(prior_syms - current_syms) if prior_syms else 0
        newcomer_ratio = newcomers / max(population, 1)
        dropout_ratio = dropouts / max(len(prior_syms), 1)

        # Rank entropy
        if current_ranks:
            rank_counts = np.bincount(current_ranks, minlength=51)
            rank_probs = rank_counts / rank_counts.sum()
            rank_probs = rank_probs[rank_probs > 0]
            entropy = float(-np.sum(rank_probs * np.log2(rank_probs)))
        else:
            entropy = 0.0

        metrics[scanner_type] = {
            "population": population,
            "newcomer_ratio": newcomer_ratio,
            "dropout_ratio": dropout_ratio,
            "rank_entropy": entropy,
            "newcomers": newcomers,
            "dropouts": dropouts,
        }

    return metrics


def evaluate_trade(
    signal: Signal,
    prices: PriceCache,
    stop_pct: float = 0.05,
    target_pct: float = 0.03,
    max_hold_minutes: int = 120,
) -> Trade | None:
    """Simulate a trade given a signal and price data.

    Uses minute bars to simulate entry, stop, target, and time-based exits.
    """
    entry_price = prices.get_price_at(signal.symbol, signal.timestamp)
    if entry_price is None or entry_price <= 0:
        return None

    df = prices.get_bars(signal.symbol)
    if df is None:
        return None

    # Get bars for the hold period
    end_time = signal.timestamp + timedelta(minutes=max_hold_minutes)
    mask = (df.index >= signal.timestamp) & (df.index <= end_time)
    hold_bars = df.loc[mask]

    if hold_bars.empty:
        return None

    trade = Trade(
        signal=signal,
        entry_time=signal.timestamp,
        entry_price=entry_price,
    )

    # Simulate bar-by-bar
    peak = entry_price
    trough = entry_price

    if signal.direction == "LONG":
        stop_price = entry_price * (1 - stop_pct)
        target_price = entry_price * (1 + target_pct)
    else:
        stop_price = entry_price * (1 + stop_pct)
        target_price = entry_price * (1 - target_pct)

    for bar_time, bar in hold_bars.iterrows():
        if signal.direction == "LONG":
            peak = max(peak, bar["high"])
            trough = min(trough, bar["low"])

            if bar["low"] <= stop_price:
                trade.exit_time = bar_time
                trade.exit_price = stop_price
                trade.exit_reason = "stop_loss"
                break
            if bar["high"] >= target_price:
                trade.exit_time = bar_time
                trade.exit_price = target_price
                trade.exit_reason = "take_profit"
                break
        else:
            peak = min(peak, bar["low"])
            trough = max(trough, bar["high"])

            if bar["high"] >= stop_price:
                trade.exit_time = bar_time
                trade.exit_price = stop_price
                trade.exit_reason = "stop_loss"
                break
            if bar["low"] <= target_price:
                trade.exit_time = bar_time
                trade.exit_price = target_price
                trade.exit_reason = "take_profit"
                break

    # Time stop if neither stop nor target hit
    if trade.exit_price is None:
        trade.exit_time = hold_bars.index[-1]
        trade.exit_price = float(hold_bars.iloc[-1]["close"])
        trade.exit_reason = "time_stop"

    # Compute P&L
    if signal.direction == "LONG":
        trade.pnl_pct = (trade.exit_price - entry_price) / entry_price
        trade.max_favorable = (peak - entry_price) / entry_price
        trade.max_adverse = (entry_price - trough) / entry_price
    else:
        trade.pnl_pct = (entry_price - trade.exit_price) / entry_price
        trade.max_favorable = (entry_price - peak) / entry_price
        trade.max_adverse = (trough - entry_price) / entry_price

    trade.pnl = trade.pnl_pct * entry_price  # Per-share P&L
    trade.hold_minutes = (trade.exit_time - trade.entry_time).total_seconds() / 60

    # Forward returns
    fwd = prices.get_forward_returns(signal.symbol, signal.timestamp, entry_price)
    trade.return_15m = fwd.get(15)
    trade.return_30m = fwd.get(30)
    trade.return_60m = fwd.get(60)

    return trade


def compute_strategy_results(strategy_id: str, strategy_name: str, trades: list[Trade]) -> StrategyResult:
    """Compute aggregate metrics from a list of trades."""
    result = StrategyResult(
        strategy_id=strategy_id,
        strategy_name=strategy_name,
        trades=trades,
    )

    if not trades:
        return result

    result.total_trades = len(trades)
    winners = [t for t in trades if t.pnl_pct > 0]
    losers = [t for t in trades if t.pnl_pct <= 0]
    result.winning_trades = len(winners)
    result.losing_trades = len(losers)
    result.win_rate = result.winning_trades / result.total_trades

    pnls = [t.pnl_pct for t in trades]
    result.avg_pnl_pct = np.mean(pnls)
    result.total_pnl = sum(t.pnl for t in trades)

    if winners:
        result.avg_win_pct = np.mean([t.pnl_pct for t in winners])
    if losers:
        result.avg_loss_pct = np.mean([abs(t.pnl_pct) for t in losers])

    total_wins = sum(t.pnl for t in winners) if winners else 0
    total_losses = abs(sum(t.pnl for t in losers)) if losers else 0
    result.profit_factor = total_wins / total_losses if total_losses > 0 else float("inf")

    result.avg_hold_minutes = np.mean([t.hold_minutes for t in trades])
    result.expectancy = (
        result.win_rate * result.avg_win_pct
        - (1 - result.win_rate) * result.avg_loss_pct
    )

    # Sharpe ratio (annualized from per-trade returns)
    if len(pnls) > 1:
        result.sharpe_ratio = float(np.mean(pnls) / np.std(pnls) * np.sqrt(252))

    # Max drawdown
    cumulative = np.cumsum(pnls)
    peak = np.maximum.accumulate(cumulative)
    drawdown = peak - cumulative
    result.max_drawdown_pct = float(np.max(drawdown)) if len(drawdown) > 0 else 0

    # Daily P&L
    for t in trades:
        day = t.entry_time.strftime("%Y%m%d")
        result.daily_pnl[day] = result.daily_pnl.get(day, 0) + t.pnl_pct

    return result


def get_available_dates() -> list[str]:
    """Get all available scanner dates."""
    if not SCANNER_BASE.exists():
        return []
    dates = sorted([
        d.name for d in SCANNER_BASE.iterdir()
        if d.is_dir() and d.name.isdigit() and len(d.name) == 8
    ])
    return dates


def save_results_to_db(results: list[StrategyResult]):
    """Save backtest results to SQLite database."""
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS backtest_results (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            run_timestamp TEXT NOT NULL,
            strategy_id TEXT NOT NULL,
            strategy_name TEXT NOT NULL,
            total_signals INTEGER,
            total_trades INTEGER,
            winning_trades INTEGER,
            losing_trades INTEGER,
            win_rate REAL,
            total_pnl REAL,
            avg_pnl_pct REAL,
            avg_win_pct REAL,
            avg_loss_pct REAL,
            profit_factor REAL,
            max_drawdown_pct REAL,
            sharpe_ratio REAL,
            avg_hold_minutes REAL,
            expectancy REAL
        );

        CREATE TABLE IF NOT EXISTS backtest_trades (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            run_timestamp TEXT NOT NULL,
            strategy_id TEXT NOT NULL,
            symbol TEXT NOT NULL,
            direction TEXT NOT NULL,
            entry_time TEXT,
            entry_price REAL,
            exit_time TEXT,
            exit_price REAL,
            exit_reason TEXT,
            pnl REAL,
            pnl_pct REAL,
            max_favorable REAL,
            max_adverse REAL,
            hold_minutes REAL,
            return_15m REAL,
            return_30m REAL,
            return_60m REAL,
            return_eod REAL,
            confidence REAL,
            scanners_present TEXT,
            metadata TEXT
        );
    """)

    run_ts = datetime.now().isoformat()

    for r in results:
        conn.execute("""
            INSERT INTO backtest_results
            (run_timestamp, strategy_id, strategy_name, total_signals, total_trades,
             winning_trades, losing_trades, win_rate, total_pnl, avg_pnl_pct,
             avg_win_pct, avg_loss_pct, profit_factor, max_drawdown_pct,
             sharpe_ratio, avg_hold_minutes, expectancy)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            run_ts, r.strategy_id, r.strategy_name, r.total_signals, r.total_trades,
            r.winning_trades, r.losing_trades, r.win_rate, r.total_pnl,
            r.avg_pnl_pct, r.avg_win_pct, r.avg_loss_pct, r.profit_factor,
            r.max_drawdown_pct, r.sharpe_ratio, r.avg_hold_minutes, r.expectancy,
        ))

        for t in r.trades:
            conn.execute("""
                INSERT INTO backtest_trades
                (run_timestamp, strategy_id, symbol, direction, entry_time, entry_price,
                 exit_time, exit_price, exit_reason, pnl, pnl_pct,
                 max_favorable, max_adverse, hold_minutes,
                 return_15m, return_30m, return_60m, return_eod,
                 confidence, scanners_present, metadata)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                run_ts, r.strategy_id, t.signal.symbol, t.signal.direction,
                t.entry_time.isoformat(), t.entry_price,
                t.exit_time.isoformat() if t.exit_time else None, t.exit_price,
                t.exit_reason, t.pnl, t.pnl_pct,
                t.max_favorable, t.max_adverse, t.hold_minutes,
                t.return_15m, t.return_30m, t.return_60m, t.return_eod,
                t.signal.confidence, ",".join(t.signal.scanners_present),
                json.dumps(t.signal.metadata),
            ))

    conn.commit()
    conn.close()
    logger.info(f"Saved {len(results)} strategy results to {DB_PATH}")
